import bannerIdImg02 from './assets/arka_divan_mebel_209600_1920x1080 (1).webp'
import articlePreviewImg01 from './assets/article-01.webp'
import articlePreviewImg02 from './assets/article-02.webp'
import articlePreviewImg03 from './assets/article-03.webp'
import productImg04 from './assets/basket.webp'
import categoryBedroomImg from './assets/category-bedroom.webp'
import categoryKitchen from './assets/category-kitchen.webp'
import categoryLivingRoomImg from './assets/category-living-room.webp'
import productImg01 from './assets/divan.webp'
import productImg03 from './assets/lamp2.webp'
import productImg02 from './assets/lamp.webp'
import bannerIdImg01 from './assets/Paste image (1) (1).webp'
import bannerIdImg03 from './assets/postel_komnata_mebel_76186_1920x1080 (1).webp'
import productImg05 from './assets/toaster.webp'

export default {
  articles: [
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      id: 1,
      imagePreview: articlePreviewImg01.src,
      isNew: true,
      name: '7 ways to decor your home',
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      id: 2,
      imagePreview: articlePreviewImg02.src,
      isNew: true,
      name: 'Kitchen organization',
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      id: 3,
      imagePreview: articlePreviewImg03.src,
      isNew: true,
      name: 'Decor your bedroom',
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
  ],
  categories: [
    {
      createdAt: 'May 5, 2024 at 2:58:14 PM UTC+3',
      id: 1,
      image: categoryLivingRoomImg.src,
      isDeleted: false,
      isDisabled: false,
      name: 'Living Room',
      parentId: null,
      slug: 'living-room',
      updatedAt: 'May 5, 2024 at 2:58:14 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 2:58:14 PM UTC+3',
      id: 2,
      image: categoryBedroomImg.src,
      isDeleted: false,
      isDisabled: false,
      name: 'Bedroom',
      parentId: null,
      slug: 'Bedroom',
      updatedAt: 'May 5, 2024 at 2:58:14 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 2:58:14 PM UTC+3',
      id: 3,
      image: categoryKitchen.src,
      isDeleted: false,
      isDisabled: false,
      name: 'Kitchen',
      parentId: null,
      slug: 'Kitchen',
      updatedAt: 'May 5, 2024 at 2:58:14 PM UTC+3',
    },
  ],
  mainSliderItems: [
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      description:
        'World class home and office furniture at never before rates',
      id: 1,
      image: bannerIdImg01.src,
      isDisabled: false,
      title: 'Modern Furniture For Sale',
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      url: '#',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      description: 'Discover your hone with modern bedroom furniture',
      id: 2,
      image: bannerIdImg02.src,
      isDisabled: false,
      title: 'Dream Bedroom',
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      url: '#',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      description: 'Enhance your home with new summer collection',
      id: 3,
      image: bannerIdImg03.src,
      isDisabled: false,
      title: 'Living Room Furniture',
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      url: '#',
    },
  ],
  products: [
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: 50,
      id: 1,
      image: productImg01.src,
      isNew: true,
      name: 'Loveseat Sofa',
      price: 400,
      priceDiscount: 199,
      rating: 5,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: null,
      id: 2,
      image: productImg02.src,
      isNew: true,
      name: 'Table Lamp',
      price: 24.99,
      priceDiscount: null,
      rating: 4.5,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: null,
      id: 3,
      image: productImg03.src,
      isNew: true,
      name: 'Beige Table Lamp',
      price: 30,
      priceDiscount: null,
      rating: 4.8,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: 10,
      id: 4,
      image: productImg04.src,
      isNew: true,
      name: 'Bamboo Basket',
      price: 18,
      priceDiscount: 16.99,
      rating: 5,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: null,
      id: 5,
      image: productImg05.src,
      isNew: true,
      name: 'Toaster',
      price: 50,
      priceDiscount: null,
      rating: 5,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: 50,
      id: 6,
      image: productImg01.src,
      isNew: true,
      name: 'Loveseat Sofa',
      price: 400,
      priceDiscount: 199,
      rating: 5,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: null,
      id: 7,
      image: productImg02.src,
      isNew: true,
      name: 'Table Lamp',
      price: 24.99,
      priceDiscount: null,
      rating: 4.5,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: null,
      id: 8,
      image: productImg03.src,
      isNew: true,
      name: 'Beige Table Lamp',
      price: 30,
      priceDiscount: null,
      rating: 4.8,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: 10,
      id: 9,
      image: productImg04.src,
      isNew: true,
      name: 'Bamboo Basket',
      price: 16.99,
      priceDiscount: 18,
      rating: 5,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
    {
      createdAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
      discountPercent: null,
      id: 10,
      image: productImg05.src,
      isNew: true,
      name: 'Toaster',
      price: 50,
      priceDiscount: null,
      rating: 5,
      updatedAt: 'May 5, 2024 at 3:01:06 PM UTC+3',
    },
  ],
} as const
