import type { DeviceType } from '@fsd/shared/lib'
import type { Metadata } from 'next'

import { QueryProvider, ShopLayout, ThemeProvider } from '@fsd/app'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { headers } from 'next/headers'
import { UAParser as parser } from 'ua-parser-js'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'yo!',
}

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const headersList = await headers()

  const deviceType =
    parser(headersList.get('user-agent') as string).device.type || 'desktop'

  return (
    <html lang="en-US">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider deviceType={deviceType as DeviceType}>
            <QueryProvider>
              <ShopLayout>{children}</ShopLayout>
            </QueryProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}

export default RootLayout
