import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { UAParser as parser } from 'ua-parser-js'
import { type DeviceType, ThemeProvider, QueryProvider } from '@fsd/shared'

export const metadata: Metadata = {
  title: 'yo!',
  description: 'Generated by create next app',
}

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const headersList = await headers()

  const deviceType =
    parser(headersList.get('user-agent') as string).device.type || 'desktop'

  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider deviceType={deviceType as DeviceType}>
            <QueryProvider>{children}</QueryProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}

export default RootLayout
